language: generic

git:
  depth: 10

env:
  global:
  - PROG_VER=$(cat VERSION.txt)

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      services:
      - docker
      before_script:
      - export ubuntu_mirror="$(grep ^deb /etc/apt/sources.list | grep ubuntu --color=never | awk '{print $2}' | sort | uniq -c | sort -nr | head -n 1 | awk '{print $2}' | awk -F '/' '{print $3}')"
      script:
      - docker run -i -v "${PWD}:/transgui" i386/ubuntu:17.04 linux32 --32bit i386 bash -c "sed -E 's/(archive|security).ubuntu.com/$ubuntu_mirror/g' -i /etc/apt/sources.list && apt update && apt install -y fpc"

