language: generic

git:
  depth: 10

env:
  global:
  - PROG_VER=$(cat VERSION.txt)

matrix:
  include:
    - os: osx
      osx_image: xcode8.3
      env:
      - task=build
      - arch=osx
      install:
      - brew install jq fpc
      - sh -c 'cd setup/macosx && ./compilers.sh'
      script:
      - echo -en 'travis_fold:start:build'
      - sh -c 'cd setup/macosx && ./create_app_new.sh'
      - echo -en 'travis_fold:end:build'

notifications:
  email:
    on_failure: true
