git:
  depth: 1

osx_image: xcode8.3
script:
  - time wget "https://downloads.sourceforge.net/project/lazarus/Lazarus%20Mac%20OS%20X%20i386/Lazarus%201.6.4/fpc-3.0.2.intel-macosx.dmg?r=&ts=$(date +%s)"
  - time wget "https://downloads.sourceforge.net/project/lazarus/Lazarus%20Mac%20OS%20X%20i386/Lazarus%201.6.4/fpc-3.0.2.intel-macosx.dmg?r=&ts=$(date +%s)&use_mirror=netix"
  - time wget "https://downloads.sourceforge.net/project/lazarus/Lazarus%20Mac%20OS%20X%20i386/Lazarus%201.6.4/fpc-3.0.2.intel-macosx.dmg?r=&ts=$(date +%s)&use_mirror=cfhcable"
  - time wget "https://downloads.sourceforge.net/project/lazarus/Lazarus%20Mac%20OS%20X%20i386/Lazarus%201.6.4/fpc-3.0.2.intel-macosx.dmg?r=&ts=$(date +%s)&use_mirror=cytranet"
  - time wget "https://downloads.sourceforge.net/project/lazarus/Lazarus%20Mac%20OS%20X%20i386/Lazarus%201.6.4/fpc-3.0.2.intel-macosx.dmg?r=&ts=$(date +%s)&use_mirror=pilotfiber"
  - time wget "https://downloads.sourceforge.net/project/lazarus/Lazarus%20Mac%20OS%20X%20i386/Lazarus%201.6.4/fpc-3.0.2.intel-macosx.dmg?r=&ts=$(date +%s)&use_mirror=superb-dca2"
  - time wget "https://downloads.sourceforge.net/project/lazarus/Lazarus%20Mac%20OS%20X%20i386/Lazarus%201.6.4/fpc-3.0.2.intel-macosx.dmg?r=&ts=$(date +%s)&use_mirror=superb-sea2"
  - time wget "https://downloads.sourceforge.net/project/lazarus/Lazarus%20Mac%20OS%20X%20i386/Lazarus%201.6.4/fpc-3.0.2.intel-macosx.dmg?r=&ts=$(date +%s)&use_mirror=svwh"
  - time wget "https://downloads.sourceforge.net/project/lazarus/Lazarus%20Mac%20OS%20X%20i386/Lazarus%201.6.4/fpc-3.0.2.intel-macosx.dmg?r=&ts=$(date +%s)&use_mirror=versaweb"
  - time wget "https://downloads.sourceforge.net/project/lazarus/Lazarus%20Mac%20OS%20X%20i386/Lazarus%201.6.4/fpc-3.0.2.intel-macosx.dmg?r=&ts=$(date +%s)&use_mirror=phoenixnap"
  - time wget "https://downloads.sourceforge.net/project/lazarus/Lazarus%20Mac%20OS%20X%20i386/Lazarus%201.6.4/fpc-3.0.2.intel-macosx.dmg?r=&ts=$(date +%s)&use_mirror=kent"
  - time wget "https://downloads.sourceforge.net/project/lazarus/Lazarus%20Mac%20OS%20X%20i386/Lazarus%201.6.4/fpc-3.0.2.intel-macosx.dmg?r=&ts=$(date +%s)&use_mirror=ayera"

notifications:
  email:
    on_failure: true
