language: generic

git:
  depth: 10

env:
  global:
  - PROG_VER=$(cat VERSION.txt)

matrix:
  include:

    - os: linux
      dist: trusty
      sudo: false
      env:
      - task=shellcheck
      addons:
        apt:
          sources:
            - debian-sid
          packages:
            - shellcheck
      script:
      - shellcheck -V
      - find . -type f -name "*.sh" | xargs -n 1 shellcheck

    - os: linux
      dist: trusty
      sudo: false
      env:
      - task=doctoc-check
      install:
      - nvm install 4
      - npm i -g doctoc
      before_script:
      - node --version
      - npm  --version
      - type doctoc
      script:
      - doctoc --title "## Table of Contents" --github README.md > /dev/null
      - if ! git diff --quiet README.md; then
          >&2 echo 'README.md "Table of Contents" dated! Please update it';
          >&2 git diff -w README.md
          exit 1;
        fi

    - os: linux
      dist: trusty
      sudo: required
      services:
      - docker
      env:
      - task=build
      - arch=amd64
      addons:
        apt:
          packages:
          - jq
      before_script:
      - export ubuntu_mirror="$(awk '/ubuntu/ {if ($1=="deb") print $2}' /etc/apt/sources.list | sort | uniq -c | sort -n | tail -n 1 | awk '{print $2}' | awk -F '/' '{print $3}')"
      script:
      - docker run -i -v "${PWD}:/transgui" ubuntu:17.04 bash -c "sed -E 's/archive.ubuntu.com/$ubuntu_mirror/g' -i /etc/apt/sources.list && cd /transgui/setup/unix/ && ./debian-ubuntu-install_deps.sh && ./build.sh"
      after_success:
      - md5sum ./Release/transgui-$PROG_VER-x86_64-Linux.txz
      - sha1sum ./Release/transgui-$PROG_VER-x86_64-Linux.txz
      - sha256sum ./Release/transgui-$PROG_VER-x86_64-Linux.txz
      - if [ -n "$TRAVIS_TAG" ] ; then curl -F "file=@./Release/transgui-$PROG_VER-x86_64-Linux.txz" -F apikey=${virustotal} https://www.virustotal.com/vtapi/v2/file/scan ; fi
      deploy:
      - provider: script
        script: setup/upload_asset.sh ./Release/transgui-$PROG_VER-x86_64-Linux.txz
        skip_cleanup: true
        on:
          tags: false
      - provider: releases
        api_key:
          secure: XfbJq1d1kstUAGoaW9NeiOOufiu/hsWgQONnTdf2fDESZSOAMR11x8bnsySlywDh2qwO3/GC1RbgTY/7ZXuzzm4vJgtl+dcxtclh4qi+hNEEkUpPWWaY0ov+45s6eR/B9H4R+7tm4ISiVgK6cgOrQQhI0AePh5/sJLBR5yVfCM9mDIoaNj0oES+oTjRixnk8srbLga6rH47xrkVTnQhWuUTQnfse1r1JgiN92lbZ1gVQGeOGdbuhztU8rcIMQEj+Nu/ub6hglf/zIPzA5D2sZnUNhURoPAb27eqWX7bXrliEXhhpCX7KTAe/wEkjtOb8LCEuSSahEAvYTXbfOBpe8AZb5tXzg2mxv0dEJLfInoSDhtZVeEBtS+q4BwVT8xLgVfRdAOUFBoKhgcayP1gL//VS1fvGEUiSh0KykDTOBBZOPfN7uu8x2nX/AZmEuwojaQ6r0UY2q1gD1d4zpfLlqCz8+RFuT9BQ9vfVdHAeO3VnDbTTQjUQNVNrDmp5yJ2b721BMXrehlqvjPoDQCPgRbxeWik4jcJKMVi3GGultCj7wmtFhuWYTf9LpSygPivBTlJggndpx8UWC/N19h/tJb2ULdVQtrmuWjs5168psQi2Eh0yjAwRQPQ3Hj5ZK9CrRy7Pic4+wh2cOjoCV1N2N5+Ky5CHyjQ8wZY4U3auAxI=
        file: ./Release/transgui-$PROG_VER-x86_64-Linux.txz
        skip_cleanup: true
        on:
          tags: true

    - os: linux
      dist: trusty
      sudo: required
      services:
      - docker
      env:
      - task=build
      - arch=i386
      addons:
        apt:
          packages:
          - jq
      before_script:
      - export ubuntu_mirror="$(awk '/ubuntu/ {if ($1=="deb") print $2}' /etc/apt/sources.list | sort | uniq -c | sort -n | tail -n 1 | awk '{print $2}' | awk -F '/' '{print $3}')"
      script:
      - docker run -i -v "${PWD}:/transgui" i386/ubuntu:17.04 linux32 --32bit i386 bash -c "sed -E 's/archive.ubuntu.com/$ubuntu_mirror/g' -i /etc/apt/sources.list && cd /transgui/setup/unix/ && ./debian-ubuntu-install_deps.sh && ./build.sh"
      after_success:
      - md5sum ./Release/transgui-$PROG_VER-i686-Linux.txz
      - sha1sum ./Release/transgui-$PROG_VER-i686-Linux.txz
      - sha256sum ./Release/transgui-$PROG_VER-i686-Linux.txz
      - if [ -n "$TRAVIS_TAG" ] ; then curl -F "file=@./Release/transgui-$PROG_VER-i686-Linux.txz" -F apikey=${virustotal} https://www.virustotal.com/vtapi/v2/file/scan ; fi
      deploy:
      - provider: script
        script: setup/upload_asset.sh ./Release/transgui-$PROG_VER-i686-Linux.txz
        skip_cleanup: true
        on:
          tags: false
      - provider: releases
        api_key:
          secure: XfbJq1d1kstUAGoaW9NeiOOufiu/hsWgQONnTdf2fDESZSOAMR11x8bnsySlywDh2qwO3/GC1RbgTY/7ZXuzzm4vJgtl+dcxtclh4qi+hNEEkUpPWWaY0ov+45s6eR/B9H4R+7tm4ISiVgK6cgOrQQhI0AePh5/sJLBR5yVfCM9mDIoaNj0oES+oTjRixnk8srbLga6rH47xrkVTnQhWuUTQnfse1r1JgiN92lbZ1gVQGeOGdbuhztU8rcIMQEj+Nu/ub6hglf/zIPzA5D2sZnUNhURoPAb27eqWX7bXrliEXhhpCX7KTAe/wEkjtOb8LCEuSSahEAvYTXbfOBpe8AZb5tXzg2mxv0dEJLfInoSDhtZVeEBtS+q4BwVT8xLgVfRdAOUFBoKhgcayP1gL//VS1fvGEUiSh0KykDTOBBZOPfN7uu8x2nX/AZmEuwojaQ6r0UY2q1gD1d4zpfLlqCz8+RFuT9BQ9vfVdHAeO3VnDbTTQjUQNVNrDmp5yJ2b721BMXrehlqvjPoDQCPgRbxeWik4jcJKMVi3GGultCj7wmtFhuWYTf9LpSygPivBTlJggndpx8UWC/N19h/tJb2ULdVQtrmuWjs5168psQi2Eh0yjAwRQPQ3Hj5ZK9CrRy7Pic4+wh2cOjoCV1N2N5+Ky5CHyjQ8wZY4U3auAxI=
        file: ./Release/transgui-$PROG_VER-i686-Linux.txz
        skip_cleanup: true
        on:
          tags: true

    - os: linux
      dist: trusty
      sudo: required
      services:
      - docker
      env:
      - task=build
      - arch=rpi-armv6l
      addons:
        apt:
          packages:
          - jq
          - qemu-user-static
      script:
      - docker run -i -v "${PWD}:/transgui" -v /usr/bin/qemu-arm-static:/usr/bin/qemu-arm-static resin/rpi-raspbian:stretch bash -c "sed -i 's/archive.raspbian.org/mirrors.ocf.berkeley.edu\/raspbian/g' /etc/apt/sources.list && cd /transgui/setup/unix/ && ./debian-ubuntu-install_deps.sh && ./build.sh"
      after_success:
      - md5sum ./Release/transgui-$PROG_VER-armv6l-Linux.txz
      - sha1sum ./Release/transgui-$PROG_VER-armv6l-Linux.txz
      - sha256sum ./Release/transgui-$PROG_VER-armv6l-Linux.txz
      - if [ -n "$TRAVIS_TAG" ] ; then curl -F "file=@./Release/transgui-$PROG_VER-armv6l-Linux.txz" -F apikey=${virustotal} https://www.virustotal.com/vtapi/v2/file/scan ; fi
      deploy:
      - provider: script
        script: setup/upload_asset.sh ./Release/transgui-$PROG_VER-armv6l-Linux.txz
        skip_cleanup: true
        on:
          tags: false
      - provider: releases
        api_key:
          secure: XfbJq1d1kstUAGoaW9NeiOOufiu/hsWgQONnTdf2fDESZSOAMR11x8bnsySlywDh2qwO3/GC1RbgTY/7ZXuzzm4vJgtl+dcxtclh4qi+hNEEkUpPWWaY0ov+45s6eR/B9H4R+7tm4ISiVgK6cgOrQQhI0AePh5/sJLBR5yVfCM9mDIoaNj0oES+oTjRixnk8srbLga6rH47xrkVTnQhWuUTQnfse1r1JgiN92lbZ1gVQGeOGdbuhztU8rcIMQEj+Nu/ub6hglf/zIPzA5D2sZnUNhURoPAb27eqWX7bXrliEXhhpCX7KTAe/wEkjtOb8LCEuSSahEAvYTXbfOBpe8AZb5tXzg2mxv0dEJLfInoSDhtZVeEBtS+q4BwVT8xLgVfRdAOUFBoKhgcayP1gL//VS1fvGEUiSh0KykDTOBBZOPfN7uu8x2nX/AZmEuwojaQ6r0UY2q1gD1d4zpfLlqCz8+RFuT9BQ9vfVdHAeO3VnDbTTQjUQNVNrDmp5yJ2b721BMXrehlqvjPoDQCPgRbxeWik4jcJKMVi3GGultCj7wmtFhuWYTf9LpSygPivBTlJggndpx8UWC/N19h/tJb2ULdVQtrmuWjs5168psQi2Eh0yjAwRQPQ3Hj5ZK9CrRy7Pic4+wh2cOjoCV1N2N5+Ky5CHyjQ8wZY4U3auAxI=
        file: ./Release/transgui-$PROG_VER-armv6l-Linux.txz
        skip_cleanup: true
        on:
          tags: true

    - os: osx
      osx_image: xcode8.3
      env:
      - task=build
      - arch=osx
      - sourceforge_mirror=pilotfiber
      install:
      - brew install jq
      - sh -c 'cd setup/macosx && ./compilers.sh'
      script:
      - echo -en 'travis_fold:start:build'
      - sh -c 'cd setup/macosx && ./create_app_new.sh'
      - echo -en 'travis_fold:end:build'
      after_success:
      - md5 ./setup/macosx/transgui-$PROG_VER.dmg
      - shasum -a 1 ./setup/macosx/transgui-$PROG_VER.dmg
      - shasum -a 256 ./setup/macosx/transgui-$PROG_VER.dmg
      - if [ -n "$TRAVIS_TAG" ] ; then curl -F "file=@./setup/macosx/transgui-$PROG_VER.dmg" -F apikey=${virustotal} https://www.virustotal.com/vtapi/v2/file/scan ; fi
      deploy:
      - provider: script
        script: setup/upload_asset.sh ./setup/macosx/transgui-$PROG_VER.dmg
        skip_cleanup: true
        on:
          tags: false
      - provider: releases
        api_key:
          secure: XfbJq1d1kstUAGoaW9NeiOOufiu/hsWgQONnTdf2fDESZSOAMR11x8bnsySlywDh2qwO3/GC1RbgTY/7ZXuzzm4vJgtl+dcxtclh4qi+hNEEkUpPWWaY0ov+45s6eR/B9H4R+7tm4ISiVgK6cgOrQQhI0AePh5/sJLBR5yVfCM9mDIoaNj0oES+oTjRixnk8srbLga6rH47xrkVTnQhWuUTQnfse1r1JgiN92lbZ1gVQGeOGdbuhztU8rcIMQEj+Nu/ub6hglf/zIPzA5D2sZnUNhURoPAb27eqWX7bXrliEXhhpCX7KTAe/wEkjtOb8LCEuSSahEAvYTXbfOBpe8AZb5tXzg2mxv0dEJLfInoSDhtZVeEBtS+q4BwVT8xLgVfRdAOUFBoKhgcayP1gL//VS1fvGEUiSh0KykDTOBBZOPfN7uu8x2nX/AZmEuwojaQ6r0UY2q1gD1d4zpfLlqCz8+RFuT9BQ9vfVdHAeO3VnDbTTQjUQNVNrDmp5yJ2b721BMXrehlqvjPoDQCPgRbxeWik4jcJKMVi3GGultCj7wmtFhuWYTf9LpSygPivBTlJggndpx8UWC/N19h/tJb2ULdVQtrmuWjs5168psQi2Eh0yjAwRQPQ3Hj5ZK9CrRy7Pic4+wh2cOjoCV1N2N5+Ky5CHyjQ8wZY4U3auAxI=
        file: ./setup/macosx/transgui-$PROG_VER.dmg
        skip_cleanup: true
        on:
          tags: true

notifications:
  email:
    on_failure: true
